#!/usr/bin/env ruby

# Trap ^C
Signal.trap("INT") {
  puts "\nCtrl-C detected. Exiting..."
  sleep 0.1
  exit
}

$:.unshift(File.expand_path("../../lib", __FILE__))
require "google-ssl-cert"
require "google_ssl_cert/cli"

GoogleSslCert::CLI.start(ARGV)
